
["Gameplay Settings"]
	#Pickup delay after dropping items
	#Default = 20
	#Vanilla = 40
	"Pickup Delay" = 20
	#Should item entities have physical aspects such as collision boxes?
	#Default = true
	#Vanilla = false
	"Item Physics" = false
	#Should item entities be picked up automatically?
	#Default = false
	#Vanilla = true
	"Automatic Pickup" = true
	#Should item entities only be picked up when sneaking?
	#Default = false
	#Vanilla = false
	"Sneaking Pickup" = false
	#Should item entities be combined in the world?
	#Default = false
	#Vanilla = true
	Combining = true
	#Tools which enable picking up items automatically when held in the off-hand
	"Collection Tool" = []
	#Tools which enable picking up items automatically when held
	"Collection Tool Hand" = "OFF_HAND"

["Rendering Settings"]
	#Strength of the angular variation
	#Default = 10
	#Vanilla = 0
	Variation = 10
	#Should item entities have a bob effect?
	#Default = false
	#Vanilla = true
	Bob = false
	#Should item entities rotate?
	#Default = false
	#Vanilla = true
	Rotate = false

